name: Android CI

on:
  push:
    branches: [ "dev", "main", "feature/**" ]
    tags:     [ "v*.*.*" ]
    paths:
      - '.github/workflows/android.yml'
      - 'gradlew*'
      - 'settings.gradle*'
      - 'build.gradle*'
      - 'app/**'
      - 'gradle/**'
  pull_request:
    branches: [ "dev", "main" ]
    paths:
      - 'gradlew*'
      - 'settings.gradle*'
      - 'build.gradle*'
      - 'app/**'
      - 'gradle/**'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Läuft immer, aber bricht NIE ab. Dient als Statusanzeige, solange kein Projekt vorhanden ist.
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for Android project
        id: probe
        run: |
          if [ -f "gradlew" ]; then
            echo "found_gradle=true" >> $GITHUB_OUTPUT
            echo "✅ Android project detected."
          else
            echo "found_gradle=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No Android project yet. CI will stay idle until code is pushed."
          fi

  checks:
    name: Lint & Unit Tests
    needs: pr
